apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umgapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<GITHUB_USERNAME>/<REPO_NAME>
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
