apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../kubernetes/01-namespace.yaml
  - ../kubernetes/02-service-account.yaml
  - ../kubernetes/03-configmap.yaml
  - ../kubernetes/04-deployment.yaml
  - ../kubernetes/05-service.yaml
  - ../kubernetes/06-hpa.yaml
  - ../ingress/nginx-ingress.yaml
  - ../argocd/argocd-install.yaml
  - ../argocd/ingress.yaml
  - ../argocd/application.yaml

commonLabels:
  app.kubernetes.io/name: umgapi-app
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  project: umgapi-gitops

# Enable image update via kustomize
images:
  - name: umgapi-app
    newName: 014772274523.dkr.ecr.us-east-1.amazonaws.com/umgapi-app
    newTag: v1.0.0
