# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "umgapi-tfstate-bucket"
    encrypt      = true
    key          = "dev/dev/cluster/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
