---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
  annotations:
    # This annotation enables IRSA binding to the IAM role created by Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::014772274523:role/umgapi-cluster-dev-node-role
